import './globals.css'
import { Barlow } from 'next/font/google'
import Header from '../components/Header';

const barlow = Barlow({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
